### ISSUE TITLE
titlebar maximize/ fullScreen problem

### ISSUE THREAD

**Issue by fuluboy** [yjlintw/comic-reader#82]
titlebar maximize/ fullScreen button not work after click.

**Comment by yjlintw** [comment]
We might need to implement different titlebar depending on the user's OS system

**Comment by yjlintw** [comment]
Related to #80

**Comment by yjlintw** [comment]
I think that is a issue related to electron, will report to electron.

https://github.com/electron/electron/issues/8488
https://github.com/electron/electron/issues/9092

**Comment by yjlintw** [comment]
temporarily fixed in #100.
We maintained our boolean variable to see whether the app is maximized.
We also checked whether the app's size is as same as the working area on start up, if it is true, we make it 10px smaller on both width and height, and make the default state is non-maximized.

The reason I do that is, if it is maximized on startup and the user tries to unmaximized it, the window will disappear (probably because the width and height are set to 0).
